.PHONY : test

define func1
	@echo "My name is $(0)"
endef

func2 := @echo "My name is $(0)"


var1 := $(call func1)
var2 := $(call func2)
var3 := $(func2)
var4 := $(abspath ./)
var5 := $(abspath makefile)

test :
	@echo "var1 => $(var1)"
	@echo "var2 => $(var2)"
	@echo "var3 => $(var3)"
	@echo "var4 => $(var4)"
	@echo "var5 => $(var5)"

#var1 => 	@echo My name is func1
#var2 => @echo My name is 
#var3 => @echo My name is 
#var4 => /home/cuibin/work/DiTai/makefile/LearnMakeFile/class_09
#var5 => /home/cuibin/work/DiTai/makefile/LearnMakeFile/class_09/makefile
