
include $(MOD_CFG)

# customization begin
#
# DIR_SRC := src
# DIR_INC := inc
#
# TYPE_INC := .h
# TYPE_SRC := .c
# TYPE_OBJ := .o
# TYPE_DEP := .dep
#
# customization end

include $(CMD_CFG)

include $(MOD_RULE)

